/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobId = IDL.Nat;
export const ExperienceLevel = IDL.Variant({
  'mid' : IDL.Null,
  'lead' : IDL.Null,
  'senior' : IDL.Null,
  'entry' : IDL.Null,
});
export const EducationLevel = IDL.Variant({
  'phd' : IDL.Null,
  'highSchool' : IDL.Null,
  'masters' : IDL.Null,
  'bachelors' : IDL.Null,
  'notRequired' : IDL.Null,
});
export const JobRequirements = IDL.Record({
  'otherRequirements' : IDL.Vec(IDL.Text),
  'experienceLevel' : ExperienceLevel,
  'minYearsExperience' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
  'educationLevel' : EducationLevel,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const CandidateProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'requirements' : JobRequirements,
});
export const MatchId = IDL.Nat;
export const RequirementScore = IDL.Record({
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'requirement' : IDL.Text,
});
export const ResumeId = IDL.Nat;
export const MatchResult = IDL.Record({
  'id' : MatchId,
  'matchedAt' : Timestamp,
  'overallScore' : IDL.Nat,
  'breakdown' : IDL.Vec(RequirementScore),
  'jobId' : JobId,
  'resumeId' : ResumeId,
  'candidateId' : UserId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Resume = IDL.Record({
  'id' : ResumeId,
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
  'candidateId' : UserId,
  'uploadedAt' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeJob' : IDL.Func([JobId], [], []),
  'createJob' : IDL.Func([IDL.Text, IDL.Text, JobRequirements], [JobId], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateProfile' : IDL.Func([], [IDL.Opt(CandidateProfile)], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getMyMatchForJob' : IDL.Func([JobId], [IDL.Opt(MatchResult)], ['query']),
  'getMyMatches' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
  'getMyResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listCandidateProfiles' : IDL.Func(
      [],
      [IDL.Vec(CandidateProfile)],
      ['query'],
    ),
  'listOpenJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'saveCandidateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'uploadResume' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobId = IDL.Nat;
  const ExperienceLevel = IDL.Variant({
    'mid' : IDL.Null,
    'lead' : IDL.Null,
    'senior' : IDL.Null,
    'entry' : IDL.Null,
  });
  const EducationLevel = IDL.Variant({
    'phd' : IDL.Null,
    'highSchool' : IDL.Null,
    'masters' : IDL.Null,
    'bachelors' : IDL.Null,
    'notRequired' : IDL.Null,
  });
  const JobRequirements = IDL.Record({
    'otherRequirements' : IDL.Vec(IDL.Text),
    'experienceLevel' : ExperienceLevel,
    'minYearsExperience' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
    'educationLevel' : EducationLevel,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const CandidateProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  const JobStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const Job = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'requirements' : JobRequirements,
  });
  const MatchId = IDL.Nat;
  const RequirementScore = IDL.Record({
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'requirement' : IDL.Text,
  });
  const ResumeId = IDL.Nat;
  const MatchResult = IDL.Record({
    'id' : MatchId,
    'matchedAt' : Timestamp,
    'overallScore' : IDL.Nat,
    'breakdown' : IDL.Vec(RequirementScore),
    'jobId' : JobId,
    'resumeId' : ResumeId,
    'candidateId' : UserId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Resume = IDL.Record({
    'id' : ResumeId,
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
    'candidateId' : UserId,
    'uploadedAt' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeJob' : IDL.Func([JobId], [], []),
    'createJob' : IDL.Func([IDL.Text, IDL.Text, JobRequirements], [JobId], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateProfile' : IDL.Func(
        [],
        [IDL.Opt(CandidateProfile)],
        ['query'],
      ),
    'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getMyMatchForJob' : IDL.Func([JobId], [IDL.Opt(MatchResult)], ['query']),
    'getMyMatches' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
    'getMyResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listCandidateProfiles' : IDL.Func(
        [],
        [IDL.Vec(CandidateProfile)],
        ['query'],
      ),
    'listOpenJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'saveCandidateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'uploadResume' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };