/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CandidateProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
}
export type EducationLevel = { 'phd' : null } |
  { 'highSchool' : null } |
  { 'masters' : null } |
  { 'bachelors' : null } |
  { 'notRequired' : null };
export type ExperienceLevel = { 'mid' : null } |
  { 'lead' : null } |
  { 'senior' : null } |
  { 'entry' : null };
export type ExternalBlob = Uint8Array;
export interface Job {
  'id' : JobId,
  'status' : JobStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'requirements' : JobRequirements,
}
export type JobId = bigint;
export interface JobRequirements {
  'otherRequirements' : Array<string>,
  'experienceLevel' : ExperienceLevel,
  'minYearsExperience' : bigint,
  'skills' : Array<string>,
  'educationLevel' : EducationLevel,
}
export type JobStatus = { 'closed' : null } |
  { 'open' : null };
export type MatchId = bigint;
export interface MatchResult {
  'id' : MatchId,
  'matchedAt' : Timestamp,
  'overallScore' : bigint,
  'breakdown' : Array<RequirementScore>,
  'jobId' : JobId,
  'resumeId' : ResumeId,
  'candidateId' : UserId,
}
export interface RequirementScore {
  'feedback' : string,
  'score' : bigint,
  'requirement' : string,
}
export interface Resume {
  'id' : ResumeId,
  'blob' : ExternalBlob,
  'filename' : string,
  'candidateId' : UserId,
  'uploadedAt' : Timestamp,
}
export type ResumeId = bigint;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeJob' : ActorMethod<[JobId], undefined>,
  'createJob' : ActorMethod<[string, string, JobRequirements], JobId>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateProfile' : ActorMethod<[], [] | [CandidateProfile]>,
  'getJob' : ActorMethod<[JobId], [] | [Job]>,
  'getMyMatchForJob' : ActorMethod<[JobId], [] | [MatchResult]>,
  'getMyMatches' : ActorMethod<[], Array<MatchResult>>,
  'getMyResume' : ActorMethod<[], [] | [Resume]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllJobs' : ActorMethod<[], Array<Job>>,
  'listCandidateProfiles' : ActorMethod<[], Array<CandidateProfile>>,
  'listOpenJobs' : ActorMethod<[], Array<Job>>,
  'saveCandidateProfile' : ActorMethod<[string, string], undefined>,
  'setOpenAiApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadResume' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];